# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85b4caa0dfbb3cc53ef24ab710acf4ea0ceaa3a838033c582d508b7df74fdc7580acdc42fa5437a7dc1ce7b0171a6827ef34e47a89e28dcc38cfb1c8b3e9ebc0

test:
  secret_key_base: d6487ff877c1712da67fda7fb46a80a3687b6515cc25f2e8894b965b580e17c27dc8d84d2069fde7ddafda412abd359bad2fc6bcd55518088de51d53d2b746af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
